- name: install mysql
  apt:
    name: mysql
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: inicie o serviço mysql
  shell: "service mysql start"

- name: certifique-se de que o mysql está habilitado para ser executado na inicialização
  service:
    name: mysql
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  mysql_user:
    name: "{{ dbuser }}"
    host: "{{ dbhost }}"
    password: "{{ dbpass }}"
    login_user: "{{ dbuser }}"
    login_password: "{{ dbpass }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: create a new database
  mysql_db:
    name: "{{ dbname }}"
    state: present
    login_user: "{{ dbuser }}"
    login_password: "{{ dbpass }}"

- name: add sample data to database
  copy:
    src: dump.sql
    dest: /tmp/dump.sql

- name: insert sample data into database
  mysql_db:
    name: "{{ dbname }}"
    state: import
    target: /tmp/dump.sql
    login_user: "{{ dbuser }}"
    login_password: "{{ dbpass }}"
